FROM python:3-alpine

ENV DATA_FOLDER /dataSuppressor

RUN apk --no-cache add py3-pip git

# Copy app scripts
COPY ./dataManager/requirements.txt $DATA_FOLDER/
COPY ./dataManager/purgeData.py  $DATA_FOLDER/

RUN pip3 install -r $DATA_FOLDER/requirements.txt
